name: Release

on: push

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: pnpm lint

  tests:
    name: Tests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: pnpm test:coverage
